const INITIAL_START = 0;
const OPTION_HEIGHT = 40;
const SELECT_HEIGHT = 400;
const VISIBILITY_SIZE = 10;
const BUFFER_SIZE = 10;

export {
  INITIAL_START,
  OPTION_HEIGHT,
  SELECT_HEIGHT,
  VISIBILITY_SIZE,
  BUFFER_SIZE,
};
